version: '4.14'

services: 
    mysqldb:
        image: mysql:latest
        ports:
        - 3306:3306
        environment: 
        - MYSQL_ROOT_PASSWORD=root
        volumes: 
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
    
    docker-python:
        build:
            context: .
        ports:
        - 3000:5000
        depends_on: 
            - mysqldb

volumes: 
    mysqlVolume:
    mysqlConfig: